### ISSUE TITLE
Cargo doesn't get installed on mac for me

### ISSUE THREAD

**Issue by CryZe** [hecrj/setup-rust-action#4]
I'm not sure what I'm doing wrong, but cargo isn't actually being installed on macOS with this.

https://github.com/CryZe/livesplit-core/runs/219750801

As you can see, the setup rust action took 1s and it fails to find cargo afterwards.

```yaml
      - name: Install Rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.toolchain }}

      - name: Build Static Library (cargo)
        if: matrix.cross == 'skip'
        run: cargo build -p staticlib --target ${{ matrix.target }} --release
```

This is more or less what is being run. `matrix.toolchain` is actually empty in this case, so it should default to `stable`.
